import Head from 'next/head';
import Link from 'next/link';
import React, { useState, type ReactNode } from 'react';
import SearchBar from './search-bar';
import Sun from '../assets/sun';
import Moon from '../assets/moon';

export default function Layout({
  children,
  home,
}:
  {
    children: ReactNode,
    home?: boolean,
  }) {
  const handleToggleDarkMode = () => {
    const nextDarkMode = !darkMode;
    setDarkMode(nextDarkMode);
    if (nextDarkMode) {
      document.documentElement.classList.add('dark');
      localStorage.setItem('color-theme', 'dark');
    }
    else {
      document.documentElement.classList.remove('dark');
      localStorage.setItem('color-theme', 'light');
    }
  }

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className="bg-notehub-light text-notehub-dark dark:bg-notehub-dark dark:text-notehub-light">
      <Head>
        <title>NoteHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex flex-row w-screen items-center fixed bg-notehub-primary gap-3">
        <Link className="ml-2 bg-notehub-secondary rounded-xl text-lg font-extrabold text-notehub-light px-3 py-1 hover:bg-notehub-secondary/80" href="/">
          NoteHub
        </Link>
        <SearchBar />
        <div>
          <button
            id="theme-toggle"
            type="button"
            className="bg-notehub-secondary px-2 py-2 rounded-full hover:bg-notehub-secondary/80"
            onClick={handleToggleDarkMode}
          >
            {darkMode ?
              (
                <Moon className='fill-notehub-tertiary w-5 h-5'/>
              ) : (
                <Sun className='fill-notehub-tertiary w-5 h-5'/>
              )
            }
          </button>
        </div>
      </header>
      <main className='flex min-h-screen flex-col items-center justify-center'>
        {children}
      </main>
      {!home && (
        <div className="table-footer-group">
          <Link href="/">← Back to home</Link>
        </div>
      )}
    </div>
  );
}