import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import React, { useState, type ReactNode } from "react";
import SearchBar from "./search-bar";
import Sun from "../assets/sun";
import Moon from "../assets/moon";
import { useSession } from "next-auth/react";
import { signIn, signOut } from "next-auth/react";

export default function Layout({ children }: { children: ReactNode }) {
  const handleToggleDarkMode = () => {
    const nextDarkMode = !darkMode;
    setDarkMode(nextDarkMode);
    if (nextDarkMode) {
      document.documentElement.classList.add("dark");
      localStorage.setItem("color-theme", "dark");
    } else {
      document.documentElement.classList.remove("dark");
      localStorage.setItem("color-theme", "light");
    }
  };

  const [darkMode, setDarkMode] = useState(false);
  const { data } = useSession();

  return (
    <div className="h-max min-h-screen bg-notehub-light text-notehub-dark dark:bg-notehub-dark dark:text-notehub-light">
      <Head>
        <title>NoteHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex w-full flex-row justify-between bg-notehub-primary text-notehub-light">
        <div className="ml-2 flex flex-row items-center justify-start gap-3">
          <Link
            href="/"
            className="rounded-xl bg-notehub-secondary px-3 py-1 text-lg font-extrabold hover:bg-notehub-secondary/80"
          >
            NoteHub
          </Link>
          <SearchBar />
          <button
            id="theme-toggle"
            type="button"
            className="rounded-full bg-notehub-secondary px-2 py-2 hover:bg-notehub-secondary/80"
            onClick={handleToggleDarkMode}
          >
            {darkMode ? (
              <Moon className="h-5 w-5 fill-notehub-tertiary" />
            ) : (
              <Sun className="h-5 w-5 fill-notehub-tertiary" />
            )}
          </button>
        </div>
        <div className="mr-2 flex flex-row items-center justify-start justify-items-center gap-3">
          <Link
            href={"/create"}
            className="rounded-xl bg-notehub-secondary px-3 py-1 text-lg font-extrabold hover:bg-notehub-secondary/80"
          >
            +
          </Link>
          <Image
            src={data?.user?.image ?? ""}
            alt="?"
            width="30"
            height="30"
            className="rounded-sm duration-150 hover:rounded-xl"
          />
          <LogIn />
        </div>
      </header>
      <main>{children}</main>
    </div>
  );
}

const LogIn: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <button
      className="rounded-xl bg-notehub-secondary px-3 py-1 text-lg font-extrabold hover:bg-notehub-secondary/80"
      onClick={sessionData ? () => void signOut() : () => void signIn()}
    >
      {sessionData ? "Sign out" : "Sign in"}
    </button>
  );
};
